export const UNAUTHENTICATED_ERROR_CODE = "UNAUTHENTICATED_ERROR";
export const UNAUTHENTICATED_ERROR_STATUS_CODE = 401;

export const INVALID_EMAIL_OR_PASSWORD_ERROR_CODE =
  "INVALID_EMAIL_OR_PASSWORD_ERROR";
export const INVALID_EMAIL_OR_PASSWORD_ERROR_STATUS_CODE = 400;
export const INVALID_EMAIL_OR_PASSWORD_ERROR_DEFAULT_MESSAGE =
  "Invalid email or password.";

export const EMAIL_NOT_VERIFIED_ERROR_CODE = "EMAIL_NOT_VERIFIED_ERROR";
export const EMAIL_NOT_VERIFIED_ERROR_STATUS_CODE = 403;
