/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as AuthenticatedRouteRouteImport } from "./routes/_authenticated/route";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as R500IndexRouteImport } from "./routes/500/index";
import { Route as AuthenticatedOnboardIndexRouteImport } from "./routes/_authenticated/onboard/index";
import { Route as AuthenticatedDashboardIndexRouteImport } from "./routes/_authenticated/dashboard/index";
import { Route as AuthenticatedAccountIndexRouteImport } from "./routes/_authenticated/account/index";
import { Route as authVerifyEmailIndexRouteImport } from "./routes/(auth)/verify-email/index";
import { Route as authSignUpIndexRouteImport } from "./routes/(auth)/sign-up/index";
import { Route as authSignInIndexRouteImport } from "./routes/(auth)/sign-in/index";
import { Route as authEmailVerificationIndexRouteImport } from "./routes/(auth)/email-verification/index";
import { Route as ApiAuthSplatRouteImport } from "./routes/api/auth/$";
import { Route as authEmailVerificationResendIndexRouteImport } from "./routes/(auth)/email-verification/resend/index";

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: "/_authenticated",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const R500IndexRoute = R500IndexRouteImport.update({
  id: "/500/",
  path: "/500/",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedOnboardIndexRoute =
  AuthenticatedOnboardIndexRouteImport.update({
    id: "/onboard/",
    path: "/onboard/",
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any);
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: "/dashboard/",
    path: "/dashboard/",
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any);
const AuthenticatedAccountIndexRoute =
  AuthenticatedAccountIndexRouteImport.update({
    id: "/account/",
    path: "/account/",
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any);
const authVerifyEmailIndexRoute = authVerifyEmailIndexRouteImport.update({
  id: "/(auth)/verify-email/",
  path: "/verify-email/",
  getParentRoute: () => rootRouteImport,
} as any);
const authSignUpIndexRoute = authSignUpIndexRouteImport.update({
  id: "/(auth)/sign-up/",
  path: "/sign-up/",
  getParentRoute: () => rootRouteImport,
} as any);
const authSignInIndexRoute = authSignInIndexRouteImport.update({
  id: "/(auth)/sign-in/",
  path: "/sign-in/",
  getParentRoute: () => rootRouteImport,
} as any);
const authEmailVerificationIndexRoute =
  authEmailVerificationIndexRouteImport.update({
    id: "/(auth)/email-verification/",
    path: "/email-verification/",
    getParentRoute: () => rootRouteImport,
  } as any);
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: "/api/auth/$",
  path: "/api/auth/$",
  getParentRoute: () => rootRouteImport,
} as any);
const authEmailVerificationResendIndexRoute =
  authEmailVerificationResendIndexRouteImport.update({
    id: "/(auth)/email-verification/resend/",
    path: "/email-verification/resend/",
    getParentRoute: () => rootRouteImport,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/500/": typeof R500IndexRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/email-verification/": typeof authEmailVerificationIndexRoute;
  "/sign-in/": typeof authSignInIndexRoute;
  "/sign-up/": typeof authSignUpIndexRoute;
  "/verify-email/": typeof authVerifyEmailIndexRoute;
  "/account/": typeof AuthenticatedAccountIndexRoute;
  "/dashboard/": typeof AuthenticatedDashboardIndexRoute;
  "/onboard/": typeof AuthenticatedOnboardIndexRoute;
  "/email-verification/resend/": typeof authEmailVerificationResendIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/500": typeof R500IndexRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/email-verification": typeof authEmailVerificationIndexRoute;
  "/sign-in": typeof authSignInIndexRoute;
  "/sign-up": typeof authSignUpIndexRoute;
  "/verify-email": typeof authVerifyEmailIndexRoute;
  "/account": typeof AuthenticatedAccountIndexRoute;
  "/dashboard": typeof AuthenticatedDashboardIndexRoute;
  "/onboard": typeof AuthenticatedOnboardIndexRoute;
  "/email-verification/resend": typeof authEmailVerificationResendIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/_authenticated": typeof AuthenticatedRouteRouteWithChildren;
  "/500/": typeof R500IndexRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/(auth)/email-verification/": typeof authEmailVerificationIndexRoute;
  "/(auth)/sign-in/": typeof authSignInIndexRoute;
  "/(auth)/sign-up/": typeof authSignUpIndexRoute;
  "/(auth)/verify-email/": typeof authVerifyEmailIndexRoute;
  "/_authenticated/account/": typeof AuthenticatedAccountIndexRoute;
  "/_authenticated/dashboard/": typeof AuthenticatedDashboardIndexRoute;
  "/_authenticated/onboard/": typeof AuthenticatedOnboardIndexRoute;
  "/(auth)/email-verification/resend/": typeof authEmailVerificationResendIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/500/"
    | "/api/auth/$"
    | "/email-verification/"
    | "/sign-in/"
    | "/sign-up/"
    | "/verify-email/"
    | "/account/"
    | "/dashboard/"
    | "/onboard/"
    | "/email-verification/resend/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/500"
    | "/api/auth/$"
    | "/email-verification"
    | "/sign-in"
    | "/sign-up"
    | "/verify-email"
    | "/account"
    | "/dashboard"
    | "/onboard"
    | "/email-verification/resend";
  id:
    | "__root__"
    | "/"
    | "/_authenticated"
    | "/500/"
    | "/api/auth/$"
    | "/(auth)/email-verification/"
    | "/(auth)/sign-in/"
    | "/(auth)/sign-up/"
    | "/(auth)/verify-email/"
    | "/_authenticated/account/"
    | "/_authenticated/dashboard/"
    | "/_authenticated/onboard/"
    | "/(auth)/email-verification/resend/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren;
  R500IndexRoute: typeof R500IndexRoute;
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute;
  authEmailVerificationIndexRoute: typeof authEmailVerificationIndexRoute;
  authSignInIndexRoute: typeof authSignInIndexRoute;
  authSignUpIndexRoute: typeof authSignUpIndexRoute;
  authVerifyEmailIndexRoute: typeof authVerifyEmailIndexRoute;
  authEmailVerificationResendIndexRoute: typeof authEmailVerificationResendIndexRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_authenticated": {
      id: "/_authenticated";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AuthenticatedRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/500/": {
      id: "/500/";
      path: "/500";
      fullPath: "/500/";
      preLoaderRoute: typeof R500IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_authenticated/onboard/": {
      id: "/_authenticated/onboard/";
      path: "/onboard";
      fullPath: "/onboard/";
      preLoaderRoute: typeof AuthenticatedOnboardIndexRouteImport;
      parentRoute: typeof AuthenticatedRouteRoute;
    };
    "/_authenticated/dashboard/": {
      id: "/_authenticated/dashboard/";
      path: "/dashboard";
      fullPath: "/dashboard/";
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport;
      parentRoute: typeof AuthenticatedRouteRoute;
    };
    "/_authenticated/account/": {
      id: "/_authenticated/account/";
      path: "/account";
      fullPath: "/account/";
      preLoaderRoute: typeof AuthenticatedAccountIndexRouteImport;
      parentRoute: typeof AuthenticatedRouteRoute;
    };
    "/(auth)/verify-email/": {
      id: "/(auth)/verify-email/";
      path: "/verify-email";
      fullPath: "/verify-email/";
      preLoaderRoute: typeof authVerifyEmailIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/(auth)/sign-up/": {
      id: "/(auth)/sign-up/";
      path: "/sign-up";
      fullPath: "/sign-up/";
      preLoaderRoute: typeof authSignUpIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/(auth)/sign-in/": {
      id: "/(auth)/sign-in/";
      path: "/sign-in";
      fullPath: "/sign-in/";
      preLoaderRoute: typeof authSignInIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/(auth)/email-verification/": {
      id: "/(auth)/email-verification/";
      path: "/email-verification";
      fullPath: "/email-verification/";
      preLoaderRoute: typeof authEmailVerificationIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/auth/$": {
      id: "/api/auth/$";
      path: "/api/auth/$";
      fullPath: "/api/auth/$";
      preLoaderRoute: typeof ApiAuthSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/(auth)/email-verification/resend/": {
      id: "/(auth)/email-verification/resend/";
      path: "/email-verification/resend";
      fullPath: "/email-verification/resend/";
      preLoaderRoute: typeof authEmailVerificationResendIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountIndexRoute: typeof AuthenticatedAccountIndexRoute;
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute;
  AuthenticatedOnboardIndexRoute: typeof AuthenticatedOnboardIndexRoute;
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountIndexRoute: AuthenticatedAccountIndexRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedOnboardIndexRoute: AuthenticatedOnboardIndexRoute,
};

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  R500IndexRoute: R500IndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  authEmailVerificationIndexRoute: authEmailVerificationIndexRoute,
  authSignInIndexRoute: authSignInIndexRoute,
  authSignUpIndexRoute: authSignUpIndexRoute,
  authVerifyEmailIndexRoute: authVerifyEmailIndexRoute,
  authEmailVerificationResendIndexRoute: authEmailVerificationResendIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
